/* Banque de tâches Sidian — générée à partir du Cursor Master File (CDC MVP).

   Chaque tâche est { t: texte, p: [paliers concernés] }.
   L'app filtre les tâches selon le PALIER de croissance courant choisi par
   l'utilisateur, puis pioche chaque jour quelques tâches réalisables par
   catégorie (rotation déterministe sur tout le réservoir éligible).
   Une tâche « cap suivant » est aussi tirée chaque jour pour préparer le
   palier d'après → réalisable aujourd'hui, mais orienté vers l'objectif futur.

   Paliers (voir window.PHASES) :
   0 Fondations · 1 Build MVP · 2 Tests & durcissement ·
   3 Bêta freelances · 4 Lancement · 5 Croissance (→ 2 000€/mois) */

window.PHASES = [
  {
    id: 0,
    name: "Fondations",
    emoji: "🧱",
    goal: "Mettre en place le socle technique : repo, comptes, variables d'env.",
    done: "Repo Next.js 14 + Supabase + Stripe Connect + Trigger.dev prêts, TS strict, CI verte.",
  },
  {
    id: 1,
    name: "Build MVP",
    emoji: "🛠️",
    goal: "Construire les 9 étapes du MVP dans l'ordre, sans rien sauter.",
    done: "Contrat → enrollment → séquence J+2/5/9 → prélèvement J+10 → dashboard fonctionnent.",
  },
  {
    id: 2,
    name: "Tests & durcissement",
    emoji: "🛡️",
    goal: "Fiabiliser : tests, sécurité, anti-double-débit, RLS, idempotency.",
    done: "Tests unit/intégration/E2E au vert + security review passée + checklist pré-deploy OK.",
  },
  {
    id: 3,
    name: "Bêta freelances",
    emoji: "🧪",
    goal: "Faire tester par de vrais freelances et corriger les frictions.",
    done: "≥ 5 freelances bêta, enrollment réel testé de bout en bout, feedback collecté.",
  },
  {
    id: 4,
    name: "Lancement",
    emoji: "🚀",
    goal: "Acquérir les premiers freelances payants et réussir les premiers prélèvements J+10.",
    done: "Premiers abonnements Pro/Business + 1er prélèvement J+10 réel réussi.",
  },
  {
    id: 5,
    name: "Croissance",
    emoji: "📈",
    goal: "Optimiser le tunnel et grimper vers 2 000€ net/mois (~83 users).",
    done: "MRR + commissions en croissance régulière vers l'objectif, V2 préparée.",
  },
];

const ALL = [0, 1, 2, 3, 4, 5];

window.CATEGORIES = [
  {
    id: "cursor",
    name: "Cursor / Dev",
    emoji: "🖱️",
    color: "#5b8cff",
    perDay: 3,
    tasks: [
      // --- Palier 0 : fondations ---
      { t: "Initialiser le repo Next.js 14 (App Router + TypeScript) avec tsconfig strict: true, zéro any.", p: [0] },
      { t: "Créer les projets/comptes : Supabase, Stripe Connect, Trigger.dev, Brevo, Resend.", p: [0] },
      { t: "Mettre en place .env.example avec toutes les clés requises (§15) — rien en dur.", p: [0, 1] },
      { t: "Configurer le déploiement Vercel + une CI minimale (typecheck + test).", p: [0, 1] },
      { t: "Créer PROMPTS.md avec les prompts Cursor réutilisables (build, review §13, sécurité §12.5).", p: [0, 1] },
      // --- Palier 1 : ordre de build MVP (§9) ---
      { t: "Core Supabase : schéma complet (freelancers, clients, contracts, invoices, enrollments, payment_intents) + types TS.", p: [0, 1] },
      { t: "Écrire/relire les RLS policies sur TOUTES les tables — un freelance ne voit jamais les données d'un autre.", p: [0, 1, 2] },
      { t: "Auth freelance : inscription + connexion + onboarding Stripe Express (compte connecté).", p: [1] },
      { t: "Création de contrat : formulaire (client, montant, fréquence one_time/monthly/quarterly, 1ère échéance) + Zod.", p: [1] },
      { t: "Génération automatique des échéances depuis first_due_date (mensuel/trimestriel) via Trigger.dev.", p: [1] },
      { t: "Enrollment client : lien public + Stripe Setup Intent + 3DS2 + texte d'autorisation + timestamp consentement.", p: [1] },
      { t: "Séquence de relance : emails J+2 / J+5 / J+9 via Brevo, déclenchés par le cron Trigger.dev.", p: [1] },
      { t: "Payment Decision Engine : logique de décision J+0 → J+10 dans lib/payment-engine.", p: [1] },
      { t: "Prélèvement J+10 : Payment Intent sur le compte connecté avec application_fee_amount = commission.", p: [1] },
      { t: "Flow anti-double-débit : matrice d'anomalies (freelance annule seul, client suspend, timer 24h).", p: [1, 2] },
      { t: "Dashboard freelance : contrats + statuts enrollment + statuts paiements + états vides.", p: [1] },
      // --- Règles non-négociables (§11) — pendant le build et le durcissement ---
      { t: "Ajouter un schéma Zod sur CHAQUE nouvel input/endpoint — aucune donnée non validée en DB.", p: [1, 2] },
      { t: "Vérifier l'idempotency key sur tous les webhooks Stripe AVANT toute écriture en DB.", p: [1, 2] },
      { t: "Logger de façon structurée chaque action critique (paiement, relance, webhook, anomalie).", p: [1, 2] },
      { t: "Vérifier que la commission n'est prise QU'À J+10 (triggered_at >= due_date + 10j).", p: [1, 2] },
      { t: "Vérifier que contract.created_at > enrolled_at avant de traiter toute séquence.", p: [1, 2] },
      { t: "Brancher le webhook Stripe d'annulation : paiement reçu J+0→J+9 → séquence annulée immédiatement.", p: [1, 2] },
      { t: "Vérifier enrollment.status = 'active' avant chaque étape de la séquence.", p: [2] },
      { t: "Activer Stripe Smart Retries + Adaptive Acceptance sur le débit J+10.", p: [2, 3] },
      // --- Qualité continue ---
      { t: "Lancer `pnpm typecheck` et corriger toute erreur avant de continuer.", p: [1, 2, 3, 4, 5] },
      { t: "Lancer `pnpm test` et garder la suite au vert.", p: [1, 2, 3, 4, 5] },
      { t: "Refactoriser un fichier qui dépasse 300 lignes en modules (kebab-case).", p: [1, 2, 5] },
      { t: "Commiter et pousser au moins une amélioration aujourd'hui (petit pas = progrès).", p: [0, 1, 2, 3, 4, 5] },
      // --- Palier 5 : perf & V2 ---
      { t: "Traquer les N+1 queries Supabase et fiabiliser les crons (queue, retries).", p: [5] },
      { t: "Préparer techniquement la V2 (import PDF IA, Fintecture VRP, Web Push) sans casser le MVP.", p: [5] },
    ],
  },
  {
    id: "tests",
    name: "Tests & Sécurité",
    emoji: "🛡️",
    color: "#ef4444",
    perDay: 1,
    tasks: [
      { t: "Tests unitaires lib/payment-engine : séquence J+2/J+5/J+9/J+10 + détection anomalies.", p: [1, 2] },
      { t: "Tests unitaires lib/stripe : calcul commission, idempotency, gestion des erreurs carte.", p: [1, 2] },
      { t: "Tests unitaires lib/validations : couvrir tous les schémas Zod.", p: [1, 2] },
      { t: "Test : génération des échéances récurrentes (mensuel/trimestriel) correcte.", p: [2] },
      { t: "Test : paiement reçu à J+7 → séquence annulée → 0% commission.", p: [2] },
      { t: "Test d'intégration : webhook Stripe en doublon → idempotency → une seule action.", p: [2] },
      { t: "Test d'intégration : contrat antérieur à enrolled_at → ignoré sans exception.", p: [2] },
      { t: "Test RLS : Freelance A ne peut pas accéder aux données de Freelance B.", p: [2, 3] },
      { t: "Test E2E (Playwright) : création contrat → email enrollment envoyé.", p: [2, 3] },
      { t: "Test E2E : enrollment client → Setup Stripe 3DS2 → confirmation.", p: [2, 3] },
      { t: "Test E2E : séquence nominale échéance dépassée → J+2 → J+5 → J+9 → J+10 prélèvement.", p: [2, 3] },
      { t: "Test E2E : révocation client → enrollment annulé → freelance notifié → séquence stoppée.", p: [2, 3] },
      { t: "Passer le prompt Security Review Cursor sur les fichiers modifiés (§12.5).", p: [2, 3, 4] },
      { t: "Dérouler la review Cursor §13 : Zod ? idempotency ? RLS ? logs ? commission J+10 ? enrolled_at ?", p: [1, 2, 3] },
      { t: "Dogfood Cowork sur staging : créer un contrat + enrollment complet de bout en bout.", p: [2, 3] },
      { t: "Checklist pré-deploy §14 : typecheck, test, E2E, migrations + RLS, env Vercel, crons Trigger.dev.", p: [2, 3, 4] },
      { t: "Checklist post-deploy §14 : webhook Stripe en prod, crons actifs, contrat test carte test, J+10 en mode test.", p: [3, 4] },
    ],
  },
  {
    id: "strategie",
    name: "Stratégie",
    emoji: "🎯",
    color: "#22c55e",
    perDay: 2,
    tasks: [
      { t: "Définir précisément le critère de 'MVP fini' et ce qui te fait passer au palier suivant.", p: [0, 1] },
      { t: "Vérifier que la tâche du jour sert l'ordre de build MVP — ne rien sauter, rien ajouter hors scope.", p: [1] },
      { t: "Garder le cap : MVP = contrat manuel uniquement (pas d'intégration facturation avant V3).", p: [1, 2, 3] },
      { t: "Identifier le plus gros risque parmi les 9 points de vigilance (§16) et planifier une action.", p: [1, 2, 3, 4] },
      { t: "Re-confirmer la frontière produit : Sidian n'est PAS un EP, ni facturation, ni affacturage, ni débit SEPA.", p: [3, 4] },
      { t: "Relire le positionnement « Automatise tes paiements. Réduis tes impayés. » et vérifier la cohérence du jour.", p: [3, 4, 5] },
      { t: "Vérifier la grille tarifaire (0€/29€/59€) et la logique 'commission seulement si récupéré'.", p: [4, 5] },
      { t: "Vérifier les seuils de rentabilité Starter (carte EU 8€ / corporate 12€ / OB 6€).", p: [4, 5] },
      { t: "Suivre la cible 2 000€ net/mois (~83 users, mix 50% Starter / 35% Pro / 15% Business).", p: [4, 5] },
      { t: "Vérifier l'alignement e-facturation (sept 2026 / sept 2027) — rester natif.", p: [4, 5] },
      { t: "Décider quand lancer la V2 (import PDF / Fintecture) selon la demande réelle.", p: [5] },
      { t: "Décider d'UNE chose à NE PAS faire cette semaine pour rester focus.", p: ALL },
      { t: "Définir le prochain jalon mesurable (date + critère de réussite) de la semaine.", p: ALL },
    ],
  },
  {
    id: "marketing",
    name: "Marketing",
    emoji: "📣",
    color: "#f59e0b",
    perDay: 2,
    tasks: [
      { t: "Recruter des freelances pour la bêta (DM ciblés, communautés) — viser 5 testeurs engagés.", p: [3] },
      { t: "Build in public : poster ton avancement Sidian (LinkedIn / X) pour amorcer l'audience.", p: [3, 4, 5] },
      { t: "Préparer la page de lancement / waitlist avec l'accroche « Automatise tes paiements. Réduis tes impayés. »", p: [3, 4] },
      { t: "Publier un post sur l'impayé freelance et comment Sidian le supprime.", p: [4, 5] },
      { t: "Tester une variante de l'accroche landing et mesurer l'impact.", p: [4, 5] },
      { t: "Contacter 3 freelances cibles en DM pour comprendre leur galère d'impayés.", p: [3, 4, 5] },
      { t: "Rédiger un mini cas d'usage : facture en retard → relance J+2/J+5/J+9 → prélèvement J+10.", p: [4, 5] },
      { t: "Renforcer la confiance sur la landing (Stripe/Fintecture agréés, zéro stockage bancaire).", p: [4] },
      { t: "Travailler le framing client « Enregistre ton moyen de paiement » (comme Netflix), pas « débit auto ».", p: [4] },
      { t: "Préparer 3 idées de contenu (impayés / trésorerie freelance) et en planifier une.", p: [3, 4, 5] },
      { t: "Répondre à une question sur l'impayé dans une communauté freelance.", p: [3, 4, 5] },
      { t: "Vérifier le suivi analytics sur la landing et la page d'enrollment.", p: [3, 4] },
      { t: "Rédiger l'email de bienvenue freelance (onboarding Stripe Express en 1ère action).", p: [3, 4] },
      { t: "Créer une démo courte (GIF/vidéo) : créer un contrat → lien enrollment → dashboard.", p: [3, 4] },
      { t: "Mettre en avant l'argument « tu ne paies que si Sidian récupère vraiment ».", p: [4, 5] },
      { t: "Lister 5 mots-clés SEO (impayés freelance, relance facture, paiement automatique) et vérifier le positionnement.", p: [4, 5] },
    ],
  },
  {
    id: "produit",
    name: "Produit & Clients",
    emoji: "🧩",
    color: "#a855f7",
    perDay: 2,
    tasks: [
      { t: "Vérifier que le montant affiché/débité est toujours le `balance`, jamais le montant total.", p: [1, 2] },
      { t: "Tester le parcours client de l'enrollment comme un nouvel utilisateur et noter 3 irritants.", p: [2, 3] },
      { t: "Vérifier que l'enrollment client tient la promesse des 30 secondes.", p: [2, 3] },
      { t: "Soigner la page d'enroll (nom du freelance visible, texte d'autorisation clair, rassurant).", p: [2, 3] },
      { t: "Vérifier la lisibilité des emails J+2/J+5/J+9/J+10 (ton non agressif, anti-surprise).", p: [2, 3] },
      { t: "Tester le flow anti-double-débit côté client (« j'ai déjà payé ») et la clarté de l'alerte freelance.", p: [2, 3] },
      { t: "Clarifier dans l'UI la règle : rien d'antérieur à enrolled_at n'est débité.", p: [2, 3] },
      { t: "Vérifier les états vides du dashboard (aucun contrat / enrollment / paiement).", p: [2, 3] },
      { t: "Mettre en place un canal de feedback simple pour les freelances bêta.", p: [3] },
      { t: "Appeler un freelance bêta et noter une friction sur la création de contrat.", p: [3, 4, 5] },
      { t: "Trier le backlog : garder le top 5 aligné sur le palier courant, archiver le reste.", p: ALL },
      { t: "Recueillir un témoignage d'un freelance ayant évité un impayé grâce à Sidian.", p: [4, 5] },
    ],
  },
  {
    id: "croissance",
    name: "Croissance",
    emoji: "📈",
    color: "#06b6d4",
    perDay: 1,
    tasks: [
      { t: "Automatiser une tâche répétitive (onboarding, support) pour gagner du temps de solo founder.", p: [3, 4, 5] },
      { t: "Mettre à jour le tableau de bord : freelances inscrits, contrats créés, enrollments actifs.", p: [4, 5] },
      { t: "Analyser le tunnel inscription → Stripe Express → 1er contrat → 1er enrollment et repérer la fuite.", p: [4, 5] },
      { t: "Relancer les freelances inscrits qui n'ont pas connecté Stripe Express.", p: [4, 5] },
      { t: "Relancer les contrats créés sans enrollment client finalisé.", p: [4, 5] },
      { t: "Mesurer le taux de succès des prélèvements (cible ~95% carte seule).", p: [4, 5] },
      { t: "Suivre la progression vers 2 000€ net/mois (MRR abonnements + commissions J+10).", p: [4, 5] },
      { t: "Identifier un canal d'acquisition freelance et y consacrer plus d'efforts cette semaine.", p: [4, 5] },
      { t: "Identifier un partenariat (communautés freelances, comptables, outils de facturation).", p: [4, 5] },
      { t: "Tester une nouvelle source d'acquisition à petit budget/effort et noter le résultat.", p: [5] },
      { t: "Estimer CAC vs LTV par plan (Starter/Pro/Business), même approximatif.", p: [5] },
    ],
  },
  {
    id: "routine",
    name: "Focus & Routine",
    emoji: "🧠",
    color: "#ec4899",
    perDay: 1,
    tasks: [
      { t: "Confirmer ton palier actuel et le critère précis pour passer au suivant.", p: ALL },
      { t: "Définir LA tâche du palier courant qui rendrait la journée réussie, et la faire en premier.", p: ALL },
      { t: "Bloquer 1 h sans notifications pour du deep work.", p: ALL },
      { t: "Fin de journée : noter 1 victoire, 1 leçon, 1 priorité pour demain.", p: ALL },
      { t: "Avant de coder une feature V2/V3, se rappeler : MVP d'abord, scope verrouillé.", p: [1, 2, 3] },
      { t: "Faire une vraie pause loin de l'écran (solo founder = endurance, pas sprint).", p: ALL },
      { t: "Célébrer un petit progrès — la régularité construit Sidian, pas l'intensité ponctuelle.", p: ALL },
      { t: "Préparer la journée de demain en 3 puces ce soir.", p: ALL },
    ],
  },
];
