/* Banque de tâches pour générer la check-list quotidienne.
   Chaque catégorie possède un grand réservoir de tâches concrètes.
   L'app pioche chaque jour quelques tâches par catégorie et fait
   tourner l'ensemble du réservoir au fil des jours (rotation déterministe). */

window.CATEGORIES = [
  {
    id: "cursor",
    name: "Cursor / Dev",
    emoji: "🖱️",
    color: "#5b8cff",
    perDay: 3,
    tasks: [
      "Écrire un prompt clair dans Cursor pour la prochaine fonctionnalité (contexte + critères d'acceptation).",
      "Refactoriser un fichier qui dépasse 300 lignes en le découpant en modules.",
      "Demander à Cursor de générer des tests pour la fonction la plus critique du jour.",
      "Corriger un bug de la liste, en écrivant d'abord le test qui le reproduit.",
      "Mettre à jour le README avec la dernière fonctionnalité livrée.",
      "Faire une revue de code (Cursor « Explain ») sur un module que tu connais mal.",
      "Ajouter la gestion d'erreurs sur un appel réseau ou une requête DB non protégée.",
      "Nettoyer les `console.log` / variables mortes signalés par le linter.",
      "Créer ou améliorer un composant UI réutilisable (bouton, carte, modale).",
      "Brancher une vraie donnée à la place d'un mock dans un écran.",
      "Écrire un prompt de génération de schéma de base de données pour une table manquante.",
      "Configurer ou vérifier le pipeline CI (build + tests) sur le dépôt.",
      "Optimiser une requête lente repérée dans les logs.",
      "Ajouter un état de chargement et un état vide à un écran clé.",
      "Mettre en place le suivi d'erreurs (Sentry ou équivalent) sur une route.",
      "Documenter un prompt Cursor réutilisable dans un fichier `PROMPTS.md`.",
      "Commiter et pousser au moins une amélioration aujourd'hui (petit pas = progrès).",
      "Vérifier la responsivité mobile d'un écran avec les devtools.",
      "Ajouter une validation de formulaire côté client et serveur.",
      "Mettre à jour une dépendance et lancer la suite de tests.",
    ],
  },
  {
    id: "strategie",
    name: "Stratégie",
    emoji: "🎯",
    color: "#22c55e",
    perDay: 2,
    tasks: [
      "Réécrire en une phrase le problème que ton SaaS résout, du point de vue du client.",
      "Définir l'unique métrique nord (North Star) à suivre cette semaine.",
      "Lister 3 concurrents et noter ce qui te différencie vraiment.",
      "Choisir UNE priorité pour la semaine et écarter le reste.",
      "Estimer ton ICP (client idéal) : taille, rôle, douleur principale.",
      "Vérifier que la prochaine fonctionnalité sert un objectif business clair.",
      "Définir le pricing v1 (ou le remettre en question avec un argument).",
      "Identifier le plus gros risque actuel du projet et une action pour le réduire.",
      "Écrire ton positionnement en 2 lignes : « Pour [cible] qui [besoin], [produit] est [catégorie] qui [bénéfice]. »",
      "Décider d'une chose à NE PAS faire ce mois-ci pour rester focus.",
      "Relire tes objectifs du trimestre et vérifier que les actions du jour s'y rattachent.",
      "Calculer combien de clients il te faut pour atteindre ton premier palier de revenu.",
      "Cartographier le parcours utilisateur de la découverte à la valeur perçue.",
      "Identifier le « moment aha » de ton produit et comment l'atteindre plus vite.",
      "Décider du prochain jalon mesurable (date + critère de réussite).",
    ],
  },
  {
    id: "marketing",
    name: "Marketing",
    emoji: "📣",
    color: "#f59e0b",
    perDay: 2,
    tasks: [
      "Publier un post (LinkedIn / X) racontant un apprentissage de la journée.",
      "Écrire l'accroche (headline) de ta landing page et tester une variante.",
      "Contacter 3 prospects ou utilisateurs potentiels par message direct.",
      "Rédiger un mini cas d'usage : problème → solution → résultat.",
      "Améliorer une section de la landing page (preuve sociale, bénéfices, CTA).",
      "Préparer 3 idées de contenu pour la semaine et en planifier une.",
      "Répondre à une question dans une communauté (Reddit, Discord, forum) liée à ton domaine.",
      "Mettre en place ou vérifier le suivi analytics sur la landing page.",
      "Rédiger un email de bienvenue / d'onboarding pour les nouveaux inscrits.",
      "Lister 5 mots-clés SEO et vérifier le positionnement actuel.",
      "Créer un visuel ou une démo courte (GIF/vidéo) de la fonctionnalité phare.",
      "Demander un retour ou un témoignage à un utilisateur existant.",
      "Analyser d'où viennent tes visiteurs et doubler la source qui marche.",
      "Optimiser le CTA principal (texte, couleur, position) et noter l'hypothèse.",
      "Préparer un lead magnet simple (checklist, modèle, mini-guide).",
    ],
  },
  {
    id: "produit",
    name: "Produit & Clients",
    emoji: "🧩",
    color: "#a855f7",
    perDay: 2,
    tasks: [
      "Parler à un utilisateur (appel ou message) et noter une frustration.",
      "Trier le backlog : garder le top 5, archiver le reste.",
      "Identifier la friction n°1 de l'onboarding et proposer un correctif.",
      "Lire les retours/avis récents et en extraire une action concrète.",
      "Tester ton produit comme un nouvel utilisateur et noter 3 irritants.",
      "Définir un critère de succès pour la fonctionnalité en cours.",
      "Prioriser les tickets selon impact × effort.",
      "Vérifier un indicateur d'usage (rétention, activation) et l'interpréter.",
      "Écrire la spec courte de la prochaine fonctionnalité (1 page max).",
      "Relancer un utilisateur inactif pour comprendre pourquoi il a décroché.",
      "Simplifier un écran en retirant un élément superflu.",
      "Mettre en place un canal de feedback simple (formulaire, email, widget).",
    ],
  },
  {
    id: "croissance",
    name: "Croissance",
    emoji: "📈",
    color: "#06b6d4",
    perDay: 1,
    tasks: [
      "Mettre à jour ton tableau de bord de métriques (MRR, inscrits, churn).",
      "Tester une nouvelle source d'acquisition à petit budget/effort.",
      "Mettre en place ou améliorer un mécanisme de parrainage / partage.",
      "Analyser le tunnel de conversion et repérer la plus grosse fuite.",
      "Relancer les essais gratuits qui n'ont pas converti.",
      "Identifier un partenariat ou une intégration potentielle.",
      "Calculer ton CAC vs LTV (même approximatif) et noter l'écart.",
      "Lancer une petite expérimentation A/B et définir le critère de victoire.",
      "Automatiser une tâche répétitive pour gagner du temps cette semaine.",
      "Repérer ton canal le plus rentable et y consacrer plus d'efforts.",
    ],
  },
  {
    id: "routine",
    name: "Focus & Routine",
    emoji: "🧠",
    color: "#ec4899",
    perDay: 1,
    tasks: [
      "Définir LA tâche qui rendrait la journée réussie, et la faire en premier.",
      "Bloquer 1 h sans notifications pour du deep work.",
      "Noter en fin de journée : 1 victoire, 1 leçon, 1 priorité pour demain.",
      "Faire une pause réelle (marche, étirement) loin de l'écran.",
      "Revoir ta to-do : supprimer ce qui n'a plus d'importance.",
      "Célébrer un petit progrès — la régularité bat l'intensité.",
      "Limiter le scroll : remplacer 15 min de réseaux par 15 min de focus produit.",
      "Préparer ta journée de demain en 3 puces ce soir.",
    ],
  },
];
