/* Banque de tâches Sidian — en langage simple (pour non-dev).
   Chaque tâche est { t: texte, p: [paliers concernés] }.
   Le palier courant est déterminé automatiquement par les tâches déjà faites
   (voir app.js). L'app affiche chaque jour une courte liste tirée du palier. */

window.PHASES = [
  {
    id: 0,
    name: "Fondations",
    emoji: "🧱",
    goal: "Mettre en place les bases techniques : projet, comptes, clés.",
    done: "Projet créé, comptes des outils prêts, mise en ligne automatique qui fonctionne.",
  },
  {
    id: 1,
    name: "Construction (1ère version)",
    emoji: "🛠️",
    goal: "Construire la 1ère version étape par étape, sans rien sauter.",
    done: "Contrat → carte enregistrée → rappels → prélèvement → tableau de bord fonctionnent.",
  },
  {
    id: 2,
    name: "Fiabilisation",
    emoji: "🛡️",
    goal: "Rendre tout fiable : tests, sécurité, anti-double-paiement.",
    done: "Tests OK, relecture de sécurité faite, prêt à mettre en ligne.",
  },
  {
    id: 3,
    name: "Bêta (premiers testeurs)",
    emoji: "🧪",
    goal: "Faire tester par de vrais freelances et corriger ce qui coince.",
    done: "Au moins 5 testeurs, parcours complet validé, avis récoltés.",
  },
  {
    id: 4,
    name: "Lancement",
    emoji: "🚀",
    goal: "Avoir les premiers clients payants et les premiers prélèvements réussis.",
    done: "Premiers abonnements + 1er prélèvement automatique réussi en vrai.",
  },
  {
    id: 5,
    name: "Croissance",
    emoji: "📈",
    goal: "Améliorer et grandir vers 2 000€/mois (~83 clients).",
    done: "Revenus en hausse régulière vers l'objectif, V2 préparée.",
  },
];

const ALL = [0, 1, 2, 3, 4, 5];

window.CATEGORIES = [
  {
    id: "cursor",
    name: "Cursor / Dev",
    emoji: "🖱️",
    color: "#5b8cff",
    perDay: 3,
    tasks: [
      // --- Palier 0 : fondations ---
      { t: "Créer le projet de l'app (base Next.js) et activer les réglages stricts pour éviter les erreurs.", p: [0] },
      { t: "Créer les comptes des outils : Supabase (base de données), Stripe (paiements), Trigger.dev (tâches automatiques), Brevo et Resend (emails).", p: [0] },
      { t: "Préparer le fichier des clés secrètes (.env) — ne jamais écrire ces clés directement dans le code.", p: [0, 1] },
      { t: "Mettre l'app en ligne sur Vercel et activer la vérification automatique à chaque modification.", p: [0, 1] },
      { t: "Créer un fichier où tu notes tes meilleures consignes (prompts) à redonner à Cursor.", p: [0, 1] },
      // --- Palier 1 : construction de la 1ère version ---
      { t: "Créer la base de données : les tables freelances, clients, contrats, factures et autorisations de paiement.", p: [0, 1] },
      { t: "Sécuriser la base : chaque freelance ne voit QUE ses propres données, jamais celles des autres.", p: [0, 1, 2] },
      { t: "Créer l'inscription/connexion du freelance + le branchement de son compte Stripe pour recevoir l'argent.", p: [1] },
      { t: "Créer le formulaire de contrat : nom du client, montant, fréquence (ponctuel/mensuel/trimestriel), date de 1ère échéance.", p: [1] },
      { t: "Générer automatiquement les dates d'échéance à partir du contrat (mensuel/trimestriel).", p: [1] },
      { t: "Créer la page où le client enregistre sa carte en sécurité (Stripe), une seule fois, avec le texte d'autorisation.", p: [1] },
      { t: "Programmer les emails de rappel automatiques en cas de retard : à J+2, J+5 et J+9.", p: [1] },
      { t: "Créer la logique qui décide quoi faire jour après jour, de l'échéance jusqu'au prélèvement (J+10).", p: [1] },
      { t: "Mettre en place le prélèvement automatique à J+10, avec la commission Sidian prise au passage.", p: [1] },
      { t: "Gérer les cas spéciaux : si quelqu'un signale « déjà payé », ne pas prélever en double.", p: [1, 2] },
      { t: "Créer le tableau de bord du freelance : ses contrats, qui a enregistré sa carte, l'état des paiements.", p: [1] },
      // --- Règles importantes (pendant la construction et la fiabilisation) ---
      { t: "Vérifier chaque information saisie avant de l'enregistrer (rien d'incorrect ne doit entrer en base).", p: [1, 2] },
      { t: "Éviter les doublons : un même message reçu de Stripe ne doit jamais déclencher deux débits.", p: [1, 2] },
      { t: "Garder une trace écrite de chaque action importante (paiement, rappel, anomalie) pour vérifier après coup.", p: [1, 2] },
      { t: "Vérifier que la commission n'est JAMAIS prise avant le prélèvement réel, à J+10.", p: [1, 2] },
      { t: "Vérifier qu'on ne prélève jamais une facture plus ancienne que la date où le client a accepté.", p: [1, 2] },
      { t: "Si le client paie entre J+0 et J+9, arrêter aussitôt les rappels et ne rien prélever.", p: [1, 2] },
      { t: "Avant chaque étape, vérifier que l'autorisation du client est toujours active (pas annulée).", p: [2] },
      { t: "Activer les nouvelles tentatives automatiques de Stripe si la carte échoue le jour du prélèvement.", p: [2, 3] },
      // --- Qualité continue ---
      { t: "Lancer la vérification du code et corriger les erreurs avant de continuer.", p: [1, 2, 3, 4, 5] },
      { t: "Lancer les tests automatiques et s'assurer qu'ils passent tous.", p: [1, 2, 3, 4, 5] },
      { t: "Nettoyer un fichier devenu trop long en le découpant en morceaux plus simples.", p: [1, 2, 5] },
      { t: "Sauvegarder et envoyer au moins une amélioration aujourd'hui (un petit pas compte).", p: [0, 1, 2, 3, 4, 5] },
      // --- Palier 5 : performance & V2 ---
      { t: "Repérer les pages lentes ou les requêtes qui se répètent trop, et les rendre plus rapides.", p: [5] },
      { t: "Préparer techniquement la V2 (lecture de factures PDF, virement automatique) sans casser l'existant.", p: [5] },
    ],
  },
  {
    id: "tests",
    name: "Tests & Sécurité",
    emoji: "🛡️",
    color: "#ef4444",
    perDay: 1,
    tasks: [
      { t: "Tester la logique des rappels et du prélèvement (J+2/J+5/J+9/J+10) avec des cas fictifs.", p: [1, 2] },
      { t: "Tester les paiements : bon calcul de la commission et bonne gestion des cartes refusées.", p: [1, 2] },
      { t: "Tester que les vérifications de saisie bloquent bien les informations incorrectes.", p: [1, 2] },
      { t: "Vérifier que les échéances mensuelles/trimestrielles se créent correctement.", p: [2] },
      { t: "Tester : si le client paie à J+7, les rappels s'arrêtent et aucune commission n'est prise.", p: [2] },
      { t: "Tester qu'un message Stripe reçu deux fois ne déclenche qu'une seule action.", p: [2] },
      { t: "Tester qu'un contrat plus ancien que l'accord du client est bien ignoré.", p: [2] },
      { t: "Vérifier qu'un freelance ne peut JAMAIS voir les données d'un autre.", p: [2, 3] },
      { t: "Test complet : créer un contrat → l'email d'invitation au client part bien.", p: [2, 3] },
      { t: "Test complet : le client enregistre sa carte → il reçoit bien la confirmation.", p: [2, 3] },
      { t: "Test complet : retard → rappels J+2/J+5/J+9 → prélèvement à J+10.", p: [2, 3] },
      { t: "Test complet : le client retire son autorisation → le freelance est prévenu → tout s'arrête.", p: [2, 3] },
      { t: "Demander à Cursor une relecture de sécurité du code modifié (fuites, accès, clés en clair).", p: [2, 3, 4] },
      { t: "Repasser la check-list qualité : vérifs de saisie, anti-doublon, sécurité, traces, commission au bon moment.", p: [1, 2, 3] },
      { t: "Tester toi-même l'app sur la version de test : créer un contrat + enregistrer une carte, de A à Z.", p: [2, 3] },
      { t: "Avant une mise en ligne : tests OK, base à jour, clés bien réglées, tâches automatiques actives.", p: [2, 3, 4] },
      { t: "Après mise en ligne : vérifier en vrai que paiements, rappels et tâches automatiques fonctionnent.", p: [3, 4] },
    ],
  },
  {
    id: "strategie",
    name: "Stratégie",
    emoji: "🎯",
    color: "#22c55e",
    perDay: 2,
    tasks: [
      { t: "Écrire noir sur blanc ce qui doit marcher pour considérer la 1ère version « terminée ».", p: [0, 1] },
      { t: "Vérifier que ce que tu fais aujourd'hui fait vraiment avancer la 1ère version, sans te disperser.", p: [1] },
      { t: "Rester simple : pour l'instant, les contrats se saisissent à la main (pas d'intégration compliquée).", p: [1, 2, 3] },
      { t: "Repérer le plus gros risque du moment et prévoir une action pour le réduire.", p: [1, 2, 3, 4] },
      { t: "Se rappeler ce que Sidian n'est PAS (ni banque, ni logiciel de facture, ni rachat de créances).", p: [3, 4] },
      { t: "Vérifier que ton message reste clair : « Automatise tes paiements. Réduis tes impayés. »", p: [3, 4, 5] },
      { t: "Revoir les prix (0€ / 29€ / 59€) et le principe : commission seulement si l'argent est récupéré.", p: [4, 5] },
      { t: "Vérifier que même les petits montants restent rentables (frais de carte/virement couverts).", p: [4, 5] },
      { t: "Garder en tête l'objectif : environ 83 clients pour 2 000€ net par mois.", p: [4, 5] },
      { t: "Vérifier que tu restes en règle avec la nouvelle loi sur la facture électronique (2026 / 2027).", p: [4, 5] },
      { t: "Décider quand lancer la V2 (lecture de factures, virement) selon la vraie demande des clients.", p: [5] },
      { t: "Choisir UNE chose à NE PAS faire cette semaine pour rester concentré.", p: ALL },
      { t: "Fixer le prochain objectif concret de la semaine (avec une date et un résultat clair).", p: ALL },
    ],
  },
  {
    id: "marketing",
    name: "Marketing",
    emoji: "📣",
    color: "#f59e0b",
    perDay: 2,
    tasks: [
      { t: "Trouver des freelances pour tester l'app (messages directs, groupes) — viser 5 testeurs motivés.", p: [3] },
      { t: "Raconter ton avancement (LinkedIn / X) pour te faire connaître petit à petit.", p: [3, 4, 5] },
      { t: "Préparer la page de présentation avec l'accroche « Automatise tes paiements. Réduis tes impayés. »", p: [3, 4] },
      { t: "Publier un post sur le problème des factures impayées et comment Sidian le règle.", p: [4, 5] },
      { t: "Tester une autre phrase d'accroche sur la page et voir ce qui marche le mieux.", p: [4, 5] },
      { t: "Écrire à 3 freelances pour comprendre leur galère avec les impayés.", p: [3, 4, 5] },
      { t: "Raconter un exemple concret : facture en retard → rappels → prélèvement automatique.", p: [4, 5] },
      { t: "Rassurer sur la page : paiements gérés par Stripe, aucune donnée bancaire stockée chez toi.", p: [4] },
      { t: "Présenter ça comme « enregistre ton moyen de paiement » (comme Netflix), pas « débit automatique ».", p: [4] },
      { t: "Préparer 3 idées de publications (impayés, trésorerie freelance) et en programmer une.", p: [3, 4, 5] },
      { t: "Répondre à une question sur les impayés dans un groupe de freelances.", p: [3, 4, 5] },
      { t: "Vérifier que tu mesures bien les visites sur ta page et sur la page d'inscription du client.", p: [3, 4] },
      { t: "Écrire l'email de bienvenue du freelance (1ère étape : connecter Stripe).", p: [3, 4] },
      { t: "Faire une courte vidéo/GIF : créer un contrat → lien d'invitation → tableau de bord.", p: [3, 4] },
      { t: "Mettre en avant l'argument : « tu paies seulement si Sidian récupère vraiment ton argent ».", p: [4, 5] },
      { t: "Lister 5 mots-clés (impayés freelance, relance facture, paiement automatique) et voir où tu te places sur Google.", p: [4, 5] },
    ],
  },
  {
    id: "produit",
    name: "Produit & Clients",
    emoji: "🧩",
    color: "#a855f7",
    perDay: 2,
    tasks: [
      { t: "Vérifier qu'on affiche/prélève toujours le montant qui reste dû, jamais le total complet.", p: [1, 2] },
      { t: "Tester l'inscription côté client comme si tu étais lui, et noter 3 choses pénibles.", p: [2, 3] },
      { t: "Vérifier que le client peut enregistrer sa carte en moins de 30 secondes.", p: [2, 3] },
      { t: "Rendre la page client rassurante : nom du freelance visible, texte d'autorisation clair.", p: [2, 3] },
      { t: "Relire les emails de rappel : ton poli, pas agressif, sans mauvaise surprise.", p: [2, 3] },
      { t: "Tester le cas « j'ai déjà payé » côté client et vérifier que le freelance est bien alerté.", p: [2, 3] },
      { t: "Expliquer clairement dans l'app : rien d'avant l'accord du client n'est prélevé.", p: [2, 3] },
      { t: "Vérifier les écrans quand il n'y a encore rien (aucun contrat, aucun paiement).", p: [2, 3] },
      { t: "Mettre un moyen simple pour que les testeurs te donnent leur avis.", p: [3] },
      { t: "Appeler un freelance testeur et noter une difficulté sur la création de contrat.", p: [3, 4, 5] },
      { t: "Faire le tri dans ta liste d'idées : garder le top 5 utile maintenant, ranger le reste.", p: ALL },
      { t: "Recueillir le témoignage d'un freelance qui a évité un impayé grâce à Sidian.", p: [4, 5] },
    ],
  },
  {
    id: "croissance",
    name: "Croissance",
    emoji: "📈",
    color: "#06b6d4",
    perDay: 1,
    tasks: [
      { t: "Automatiser une tâche répétitive (accueil client, support) pour gagner du temps.", p: [3, 4, 5] },
      { t: "Mettre à jour tes chiffres clés : inscrits, contrats créés, clients ayant enregistré leur carte.", p: [4, 5] },
      { t: "Regarder où les gens décrochent (inscription → Stripe → 1er contrat → carte client) et corriger le pire point.", p: [4, 5] },
      { t: "Relancer les freelances inscrits qui n'ont pas connecté Stripe.", p: [4, 5] },
      { t: "Relancer les contrats où le client n'a pas encore enregistré sa carte.", p: [4, 5] },
      { t: "Mesurer le pourcentage de prélèvements réussis (objectif ~95%).", p: [4, 5] },
      { t: "Suivre ta progression vers 2 000€ par mois (abonnements + commissions).", p: [4, 5] },
      { t: "Choisir un canal pour trouver des freelances et y mettre plus d'efforts cette semaine.", p: [4, 5] },
      { t: "Chercher un partenaire (groupes de freelances, comptables, outils de facture).", p: [4, 5] },
      { t: "Tester une nouvelle façon d'attirer des clients, à petit budget, et noter le résultat.", p: [5] },
      { t: "Estimer combien te coûte un client vs combien il te rapporte (même approximatif).", p: [5] },
    ],
  },
  {
    id: "routine",
    name: "Focus & Routine",
    emoji: "🧠",
    color: "#ec4899",
    perDay: 1,
    tasks: [
      { t: "Faire le point : où en es-tu, et qu'est-ce qui te ferait passer à l'étape suivante ?", p: ALL },
      { t: "Choisir LA tâche la plus importante du jour et la faire en premier.", p: ALL },
      { t: "Bloquer 1 h sans notifications pour avancer au calme.", p: ALL },
      { t: "Le soir : noter 1 réussite, 1 leçon, 1 priorité pour demain.", p: ALL },
      { t: "Avant d'ajouter une nouvelle idée, se rappeler : on finit d'abord la 1ère version.", p: [1, 2, 3] },
      { t: "Faire une vraie pause loin de l'écran (c'est un marathon, pas un sprint).", p: ALL },
      { t: "Fêter un petit progrès — c'est la régularité qui construit Sidian.", p: ALL },
      { t: "Préparer ta journée de demain en 3 points ce soir.", p: ALL },
    ],
  },
];
